{% set name = "lalsimulation" %}
{% set version = "1.8.0" %}
{% set sha256 = "95ae40ddd76c78b5d30ae65ff47f0497ead7b124a447c2e04f7ad6fdaf5f232f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - make
    - {{ compiler('c') }}
  host:
    - swig >=3.0.7
    - gsl
    - lal >=6.19.0

outputs:
  - name: lalsimulation
    script: install-c.sh
    requirements:
      host:
        - {{ compiler('c') }}
        - make
        - swig >=3.0.7
        - gsl
        - lal >=6.19.0
      run:
        - gsl
        - lal >=6.19.0
    test:
      commands:
        - lalsimulation_version --verbose
        - lalsim-bh-qnmode --help
        - lalsim-bh-ringdown --help
        - lalsim-bh-sphwf --help
        - lalsim-burst --help
        - lalsim-detector-noise --help
        - lalsim-detector-strain --help
        - lalsim-inject --help
        - lalsim-inspiral --help
        - lalsim-ns-eos-table --help
        - lalsim-ns-mass-radius --help
        - lalsim-ns-params --help
        - lalsim-sgwb --help
        - lalsim-unicorn --help
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Simulation Library
      description: |
        The LSC Algorithm Simulation Library for gravitational wave data
        analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Simulation library.
  - name: python-lalsimulation
    script: install-python.sh
    requirements:
      host:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >=3.0.7
        - {{ pin_subpackage('lalsimulation', exact=True) }}
        - python
        - numpy
      run:
        - {{ pin_subpackage('lalsimulation', exact=True) }}
        - python
        - {{ pin_compatible('numpy') }}
        - python-lal >=6.19.0
    test:
      imports:
        - lalsimulation
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Simulation Library
      description: |
        The LSC Algorithm Simulation Library for gravitational wave data
        analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/DASWG/LALSuite
  license: GPLv3
  license_family: GPL
  summary: LSC Algorithm Simulation Library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
