{% set name = "lalsimulation" %}
{% set version = "4.0.1" %}

# dependencies
{% set lal_version = "7.2.0" %}
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: 085a6b9b79ea75bf12605ee3461d8378e250e2988d3c6fe7ef46cdbb3fcd074a

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - gsl
    - liblal >={{ lal_version }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]

outputs:
  - name: lalsimulation-data
    script: install-data.sh
    requirements:
      build:
        - make
      run_constrained:
        - liblalsimulation >=3.1.2
    test:
      commands:
        - test -f ${LALSIMULATION_DATADIR}/LIGO-P1200087-v18-AdV_DESIGN.txt  # [unix]
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalsimulation/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Simulation Library data files
      description: |
        The LSC Algorithm Simulation Library for gravitational wave data analysis.
        This package contains the data files needed to run various applications
        and routines that use the LAL Simulation library.

  - name: liblalsimulation
    script: install-lib.sh
    build:
      error_overdepending: true
      error_overlinking: true
      run_exports:
        - {{ pin_subpackage("liblalsimulation", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - llvm-openmp  # [osx]
        - make
        - swig >={{ swig_version }}
      host:
        - gsl
        - {{ pin_subpackage('lalsimulation-data', exact=True) }}
        - liblal >={{ lal_version }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
      run:
        - gsl
        - {{ pin_subpackage('lalsimulation-data', exact=True) }}
        - liblal >={{ lal_version }}
        - llvm-openmp  # [osx]
      run_constrained:
        - lalsimulation >=2.5.0
        - python-lalsimulation >=2.5.0
    test:
      requires:
        - pkg-config
      commands:
        # check library
        - test -f ${PREFIX}/lib/liblalsimulation${SHLIB_EXT}  # [unix]
        # check pkg-config
        - pkg-config --print-errors --exact-version "${PKG_VERSION}" lalsimulation
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalsimulation/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Simulation Library shared object libraries
      description: |
        The LSC Algorithm Simulation Library for gravitational wave data
        analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Simulation library.

  - name: python-lalsimulation
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - numpy
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - pkg-config >=0.18.0
        - swig >={{ swig_version }}
        # extras for cross-compilation:
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('liblalsimulation', exact=True) }}
        - numpy
        - python
      run:
        - {{ pin_subpackage('liblalsimulation', exact=True) }}
        - mpmath >=1.0.0
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
    test:
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
      commands:
        # only test with pytest on native platform,
        # tests run _very_ slowly when cross-compiling
        - python -m pytest -ra -v test/python  # [build_platform == target_platform]
      imports:
        - lalsimulation
        - lalsimulation.nrfits
        - lalsimulation.tilts_at_infinity
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalsimulation/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Simulation Library
      description: |
        The LSC Algorithm Simulation Library for gravitational wave data analysis.
        This package contains the Python bindings of the LALSimulation C libraries
        and additional Python modules.

        Note: this package only provides the importable Python libraries.
        All command-line interfaces, scripts, and executables are
        part of the `lalsimulation` package.

  - name: lalsimulation
    script: install-bin.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - python
      missing_dso_whitelist:
        # see https://github.com/conda/conda-build/pull/4529
        - '**/ld-linux-aarch64.so*'  # [linux and aarch64]
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - sed
      host:
        - gsl
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalsimulation', exact=True) }}
        - python
      run:
        - gsl
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalsimulation', exact=True) }}
        - python
        - {{ pin_subpackage('python-lalsimulation', exact=True) }}
    test:
      commands:
        - lalsimulation_version --verbose
        - lalsim-bh-qnmode -l 0 -m 0 -s 0
        - lalsim-bh-ringdown -M 10 -a 0 -r 100 -e 0.001 -i 0 -l 2 -m 2
        - lalsim-bh-sphwf -a 0 -l 2 -m 2 -s 0
        - lalsim-burst -w SineGaussian -q 10 -f 100 -H 1e-21 1> /dev/null
        - lalsim-detector-noise -C -t 1 -r 10
        - lalsim-detector-strain --help
        - lalsim-inject --help
        - lalsim-inspiral > /dev/null
        - lalsim-ns-eos-table -n ALF1 1> /dev/null
        - lalsim-ns-mass-radius -n ALF1 1> /dev/null
        - lalsim-ns-params -n ALF1
        - lalsim-sgwb --geo -t 1 -r 100 -W 1 1> /dev/null
        - lalsim-unicorn --help
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalsimulation/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Simulation Library
      description: |
        The LSC Algorithm Simulation Library for gravitational wave data
        analysis.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalsimulation/
  dev_url: https://git.ligo.org/lscsoft/lalsuite.git
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Simulation Library
  description: |
    The LSC Algorithm Simulation Library for gravitational wave data
    analysis.

extra:
  feedstock-name: lalsimulation
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
