travis:
  secure:
    BINSTAR_TOKEN: RsaLhuGVVSOzePxib0t7AwC2YUBmp5aYF0/3siYBWJU2FHuYJiVHMQvcG0V6siD+pR414Z375lvvC7pm1oNJpZ+jVricnk7mGG5PtsobLTWuz6rJKp5ttUE+iEMzInm87l+jdF5B8nSkgpxwwLfYjnoefcIBSqEssHt849cA7vr/pxTuvLQP99i2QBP8dL9bNKnIJbnPZMkU93MQQ/66sMZFSWLBYbPhsl8WAwZ9a/3R6cvBl/qO/iSqMU9diaBtqiyJ4gRT+vqdsdIBavWRAmxrJvhQFIRc3OvFdmO3s0SwgesXTlXjvICfcYuUJGdFvYkagdKkIx6fNjpz0/9RT0qkG03+5ClJ9E2sJVcWgLJwnVLGdweBjqRdWh2p0uqGRuz9ciR288ZAMhXPihMEx78Vilc6t39+iqswBfMyzW5tkndkHxa7u6XOk0sM0rsXf7phefz+/wBt2GxqoD2iFXKjtKfBu0YUcIJXMdvWExGjxP+1V30vUKHZKZVB1B/zPFEH2wMFxFEiSYezTJNtwpnWJ3zmnR4A9MfVGM3GtC/qLyR3LMEvSyXcxrkJU5XQwsarq2kcHWadjfUK4U+kycnFnIBnjKa3bt/hpA3xRu/XD5sJbqPMI1RsoTrryspTml6mjWieHKQbvhxhisk0fVIWEZRe4eBfDQu6lsWLtO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
